version: '3'
services:
  order_service:
    build:
      context: ./order_service
    ports:
      - "5001:5001"

  feedback_service:
    build:
      context: ./feedback_service
    ports:
      - "5003:5003"

  submit_feedback_service:
    build:
      context: ./submit_feedback_service
    ports:
      - "5005:5005"
    depends_on:
      - order_service
      - feedback_service
